#Copyright (c) Juniper Networks, Inc., 2017-2024.
#All rights reserved.

heat_template_version: 2015-04-30
parameters:
  project_name: {description: Project name, type: string}
  stack_name: {description: Stack name, type: string}
  id: {description: ID of VM, type: string}
  fpc_ip: {description: IP of FPC VM, type: string}
  re_pfe_network: {description: ID of RE-PFE, type: string}
  fabric_network: {description: ID of Fabric, type: string}
  fpc_img: {description: FPC/PFE image, type: string}
  fpc_flav: {description: Flavor of FPC Image, type: string}
  provider_net_id1: {description: Net id of provider network, type: string}

resources:
  fpc:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: fpc_flav}
      image: {get_param: fpc_img}
      name:
        str_replace:
          template: "Instance_%proj%-%ident%_fpc0"
          params:
            '%proj%': {get_param: project_name}
            '%ident%': {get_param: stack_name}
      networks:
        - port: {get_attr: [fpc_fixed_net, external_port]}
        - port: {get_attr: [fpc_fixed_net, internal_port]}
        - port: {get_attr: [fpc_ge_port1, port]} 

  fpc_fixed_net:
    type: OS::Networking::VmxFpcFixedNet
    properties:
      re_pfe_network: {get_param: re_pfe_network}
      fabric_network: {get_param: fabric_network}
      id: {get_param: id}
      internal_ip: {get_param: fpc_ip} 
      stack_name: {get_param: stack_name}

  fpc_ge_port1:
    type: OS::Networking::VmxSriovPort
    properties:
      vnetwork_id: {get_param: provider_net_id1}
      name: fpc0_WAN_0
      stack_name: {get_param: stack_name}
      vlan_filter: [3501]
      vlan_insert: true
      vlan_strip: true
      vlan_broadcast: true
      vlan_unknown_multicast: true
      vlan_unknown_unicast: true

