#Copyright (c) Juniper Networks, Inc., 2017-2024.
#All rights reserved.

heat_template_version: 2015-10-15
parameters:
  id: {description: ID of VM, type: string}
  fpc_ip: {description: IP of FPC VM, type: string}
  re_pfe_network: {description: ID of RE-PFE, type: string}
  fabric_network: {description: ID of Fabric, type: string}
  net_id1: {description: ID of ge-network, type: string}

resources:
  fpc:
    type: OS::Nova::VmxFpcSingle
    properties:
      id: 0
      re0_ip: {get_attr: [fpc_fixed_net, external_ip]}
      all_ports: [{get_attr: [fpc_fixed_net, external_port]},
                  {get_attr: [fpc_fixed_net, internal_port]},
                  {get_attr: [fpc_ge_port1, port]}]

  fpc_fixed_net:
    type: OS::Networking::VmxFpcFixedNet
    properties:
      re_pfe_network: {get_param: re_pfe_network}
      fabric_network: {get_param: fabric_network}
      id: {get_param: id}
      internal_ip: {get_param: fpc_ip} 

  fpc_ge_port1:
    type: OS::Networking::VmxPort
    properties:
      vnetwork_id: {get_param: net_id1}
      pname: fpc0_WAN_0

