#Copyright (c) Juniper Networks, Inc., 2017-2024.
#All rights reserved.

heat_template_version: 2015-10-15
parameters:
  project_name: {description: Project name, type: string}
  id: {description: Forwarding plane id, type: string}
  vfp_image: {description: Forwarding plane image, type: string}
  vfp_flavor: {description: Flavor of Forwarding plane Image, type: string}
  gateway_ip: {description: ip of gateway, type: string}
  re0_ip: {description: ip of Control Plane0, type: string}
  all_ports: {description: wan port list, type: comma_delimited_list}
  stack_name: {description: Stack name, type: string}

resources:
  fpc:
    properties:
      flavor: {get_param: vfp_flavor}
      image: {get_param: vfp_image}
      name:
        str_replace:
          template: "Instance_%proj%-%ident%_fpc%id%"
          params:
            '%proj%': {get_param: project_name}
            '%ident%': {get_param: stack_name}
            '%id%': {get_param: id}
      networks:
        repeat:
          for_each:
            <%ports%>: { get_param: all_ports }
          template:
            port: <%ports%>
    type: OS::Nova::Server

