#Copyright (c) Juniper Networks, Inc., 2017-2024.
#All rights reserved.

heat_template_version: 2015-10-15
parameters:
  ge_cidr1: {default: 20.10.15.128/24, description: CIDR GE net, type: string}
  ge_cidr2: {default: 30.10.15.128/24, description: CIDR GE net, type: string}

resources:
  br1:
    type: OS::Networking::VmxNetProvider
    properties:
      net_cidr: {get_param: ge_cidr1}
      bname: br1

  br2:
    type: OS::Networking::VmxNetProvider
    properties:
      net_cidr: {get_param: ge_cidr2}
      bname: br2

  vmx1:
    type: OS::Nova::VmxContrailSriov
    properties:
      net_id1: {get_attr: [br1, bridge_network]}
      net_id2: {get_attr: [br2, bridge_network]}

